### ISSUE TITLE
Bioships issues

### ISSUE THREAD

**Issue by Dukko** [Dukko/mergerofmods#1]
Picking Bioships from Expanded Gestalts is now more compatible, but certain models are still showing up as *non-organic*, i.e. Mobile Shipyard, Gigastructures planetcrafts etc

**Comment by LordOfLA** [comment]
That's not a bug. The ship set only supports vanilla ship types.

**Comment by Dukko** [comment]
Yup, correct. That's why I haven't marked this as a bug, but as a confirmed issue. Thanks!
