### ISSUE TITLE
Species appearance is changed game start

### ISSUE THREAD

**Issue by herki18** [Dukko/mergerofmods#10]
![image](https://user-images.githubusercontent.com/940910/116880899-7e1eb180-ac1a-11eb-8c9f-7a8a305eb79f.png)

![image](https://user-images.githubusercontent.com/940910/116881102-c211b680-ac1a-11eb-89d6-6bfc64a72269.png)

**Comment by Dukko** [comment]
This only happens if you re-use a pre-made empire created before using this modlist (or on a previous revision). Create a new empire each time.
