### ISSUE TITLE
Unemployed Pops Strata Fix

### ISSUE THREAD

**Issue by bladex1200** [Dukko/mergerofmods#14]
Mod Steam Page: https://steamcommunity.com/sharedfiles/filedetails/?id=2471020939

What it does: 

Alters the rank of unemployed pops to match the strata they are in, so that job priorities will be assigned accordingly (i.e. unemployed specialists will take specialist jobs before workers promote up to claim them) and unemployed pops of certain strata will not have to wait and downgrade just because lower-strata workers took their jobs.

**Comment by bladex1200** [comment]
I'm not allowed to change labels so I can't add the suggestions tag, apologies, not sure what's up with that.

**Comment by Dukko** [comment]
This is unneeded. The pop logic works already this way and such a change doesn't have any meaningful impact on job assignments.
