### ISSUE TITLE
Ethical Gestalts

### ISSUE THREAD

**Issue by bladex1200** [Dukko/mergerofmods#15]
Steam page: https://steamcommunity.com/sharedfiles/filedetails/?id=2476662876

What it does:

Separates gestalt consciousness from ethics, allowing gestalt empires to select ethics and thus engage in more varied and friendly diplomacy with non-gestalts. Also adds options for guest hives (bio-gestalt equivalent of branch office) and xeno residency in gestalt empires that isn't just premised around eating them, exterminating them, or integrating them.

Note: 

May have incompatibilities with ECA, additional governments, and additional civics mods. I just think it looks neat, but I understand if it's going to be a tall order to integrate this.

**Comment by BrotherWill** [comment]
There is either an option in the mod collection already that is either a trait, civic or origin (sorry I can't remember off the top of my head, but I'm really feeling it's a civic) that allows this.

**Comment by Dukko** [comment]
This would require IMMENSE patching, so it's unlikely to happen any time soon.
