### ISSUE TITLE
Planet Name Editor

### ISSUE THREAD

**Issue by BrotherWill** [Dukko/mergerofmods#17]
Planet Name Editor

Excellent quality of life mod allows to change color and add symbols to planet names making sorting and organizing easier at a glance especially with tiny GUI mods. 

Side note: The mod needs to be updated to 3.0. I noticed in the comments the mod author was working on updating. 

https://steamcommunity.com/sharedfiles/filedetails/?id=2031846653&searchtext=%22planet+name+editor%22

**Comment by Dukko** [comment]
Will add once it's updated, feel free to ping me if I don't notice the update.
