### ISSUE TITLE
Clone Vats

### ISSUE THREAD

**Issue by Arckiss** [Dukko/mergerofmods#18]
**Describe the bug**
Clone vats are unable to be built on worlds. 

**To Reproduce**
Pick the Engineering Evolution ascension perk. Go to the planetary menu and find "build clone vats" option in the side bar. There is none.

**Expected behavior**
Clone vats should be available. 

**Collection info (please complete the following information):**
 - Version Dick_0.8

**Additional context**
Played as a spiritualist empire but was also able to reproduce it with a materialist after using console commands to research the tech and give enough unity to get engineering evolution.

**Comment by Dukko** [comment]
FINALLY RESOLVED in 0.8.5
