### ISSUE TITLE
Unique and Ancient Worlds

### ISSUE THREAD

**Issue by Arckiss** [Dukko/mergerofmods#19]
**Describe the bug**
Unique and Ancient Worlds have an absence of energy, food, or minerals districts. 

**To Reproduce**
Go to the unique worlds and examine it. Naturally generated energy, food, and minerals will be absent from unique and ancient worlds. If there is a generated districts of the type mentioned in the above it will be from a planetary modifier.

**Expected behavior**
Energy, food and minerals districts should be available. 

**Screenshots**
Ideal Place: https://cdn.discordapp.com/attachments/835239395765387306/840737677015777280/Screenshot_22.png
Ideal Place with no blockers: https://cdn.discordapp.com/attachments/835239395765387306/840741670655229952/Screenshot_26.png
Torsion Coil: https://cdn.discordapp.com/attachments/835239395765387306/840739942778535946/Screenshot_24.png

**Collection info (please complete the following information):**
 - Version 6.5

**Comment by Dukko** [comment]
Cannot replicate. Anyone else has this? My unique worlds work all right.
