### ISSUE TITLE
Fast Analyzers trait blank

### ISSUE THREAD

**Issue by BrotherWill** [Dukko/mergerofmods#20]
![Screenshot_32](https://user-images.githubusercontent.com/20879881/117557469-25e41700-b041-11eb-9b22-e3b6f48f186d.png)

**Comment by BrotherWill** [comment]
Talented as well. Probably could use a full review of trait mods. 

![Screenshot_33](https://user-images.githubusercontent.com/20879881/117557508-75c2de00-b041-11eb-9f4c-3d0d2f2ab569.png)

**Comment by BrotherWill** [comment]
Yeah I saw at least 6 traits that are borked. Lazy, agressive, some others.

**Comment by matou78** [comment]
![image](https://user-images.githubusercontent.com/20770243/117566912-a5153180-b0b9-11eb-983a-03a02af5be65.png)


don't have that problem 0.8.5 ( last update as of 09/05/21)

**Comment by BrotherWill** [comment]
Unsub and resub cleared the issue. I should have tried that first.
