### ISSUE TITLE
Scaling Difficulty

### ISSUE THREAD

**Issue by CheatingChicken** [Dukko/mergerofmods#21]
Scaling difficulty gives the AI absurd buffs from the very start of the game, i assume it applies all steps of the scaling process at once

![image](https://user-images.githubusercontent.com/18604774/117573147-b0c32100-b0d6-11eb-88a4-f3d91c6f2d4a.png)
![image](https://user-images.githubusercontent.com/18604774/117573150-b3be1180-b0d6-11eb-9ebd-a6a080fa3ed2.png)
![image](https://user-images.githubusercontent.com/18604774/117573155-b6206b80-b0d6-11eb-8fe7-32fdef8f52a5.png)

**Comment by SonGorLick** [comment]
Hmmm i would say see how much fun you can have before this gets patched

**Comment by Dukko** [comment]
Can you report this to mod author to ensure it's not intended behavior?

**Comment by CheatingChicken** [comment]
Seeing how scaling difficulty is supposed to start the AI with no bonus at the beginning, that would be a pretty huge change

**Comment by Dukko** [comment]
I think you're misunderstanding what the mod does. It is not the scaling difficulty option of vanilla game. Dynamic Difficulty's scaling option ADDS modifiers over time to whatever difficulty you pick. So, it's working as intended :)
