### ISSUE TITLE
Starborn District Problems

### ISSUE THREAD

**Issue by BwenGun** [Dukko/mergerofmods#22]
Starting a new game with the 8.5 pack (with a basic merge) and the Starborn start the starting habitat is working fine, but the starborn habs you start with in your capital system and the habs you build from then on have districts that don't add anything but housing. No building slots added for the habs, and no jobs added. Example images below:

![image](https://user-images.githubusercontent.com/83912265/117574713-4ad69980-b0d6-11eb-865d-2cb355f3f6be.png)
![image](https://user-images.githubusercontent.com/83912265/117574681-28dd1700-b0d6-11eb-9faa-4f51cd5595e6.png)

I've also started a new game without merging the mod and it's the same problem.

**Comment by BwenGun** [comment]
Ok, being an idiot. Once colonised the jobs show up, but the hab districts still don't add buildings slots.

**Comment by Dukko** [comment]
Good catch. Let me see if I can figure out why.

**Comment by Dukko** [comment]
Figured it out. Issue with Lord's patch. Will let him know.
