### ISSUE TITLE
Traditional Trees

### ISSUE THREAD

**Issue by Dskod1** [Dukko/mergerofmods#26]
**Mod name**
Traditional Trees
**Mod link**
https://steamcommunity.com/sharedfiles/filedetails/?id=1703333167&searchtext=tree

Combines the traditions from Expanded Stellaris Traditions and Plentiful Traditions 3.x into a tradition tree rather than seperate traditions.

**Comment by Dukko** [comment]
That would require removing Lots of Traditions, plus I like this solution better. Thanks for the suggestion, but no :)
