### ISSUE TITLE
Archaeotech Shield Generator Relic (GPM)

### ISSUE THREAD

**Issue by WizOG** [Dukko/mergerofmods#28]
**Describe the bug**
Unable to use the planetary decision "Build shield arrays" on Capital Arcology
**To Reproduce**
- Give yourself the Archaeotech Shield Generator Relic From Guillis 
- Have a capital arcology
- Try to use the relic on the planet

**Expected behavior**
- Planet to be encased with a shield and the Planet modifier to be added
**Screenshots**
On a pc_boreal world
![image](https://user-images.githubusercontent.com/83974330/118302071-b2785480-b4db-11eb-8a92-a2be10bb44ff.png)
On a Capital arcology
![image](https://user-images.githubusercontent.com/83974330/118302159-cb810580-b4db-11eb-988c-b8dcfe0a5faa.png)

**Collection info (please complete the following information):**
 - 0.8.7.5

**Additional context**

**Comment by WizOG** [comment]
Forgot to add this does work on the Eco - Arcology
But does not work on the Fortress Arcology
Eco:
![image](https://user-images.githubusercontent.com/83974330/118302574-4ba76b00-b4dc-11eb-87a8-9f0f912a65ed.png)
Fortress:
![image](https://user-images.githubusercontent.com/83974330/118302610-57932d00-b4dc-11eb-8178-e30ef499996b.png)

**Comment by Dukko** [comment]
From my understanding, it's a bug with Guilli's mod. Please report to the author. Thanks!
