### ISSUE TITLE
[TNG] Factions Matter

### ISSUE THREAD

**Issue by Dskod1** [Dukko/mergerofmods#29]
**Mod name**
[TNG] Factions Matter
**Mod link**
https://steamcommunity.com/sharedfiles/filedetails/?id=2486579744

**Comment by Dukko** [comment]
Absolutely mega incompatible at this time, as far as I can tell. Doesn't even look like they are planning to add compatibility.

**Comment by Dskod1** [comment]
those bastards.... go ahead and close this then :(
