### ISSUE TITLE
Unity Ascension perks and Hive Minds

### ISSUE THREAD

**Issue by CheatingChicken** [Dukko/mergerofmods#30]
Hive minds seem to be able to pick two different versions of the unity Ascension perks

![image](https://user-images.githubusercontent.com/18604774/118864730-8f391500-b8e0-11eb-9d44-fe36c7c2902c.png)
![image](https://user-images.githubusercontent.com/18604774/118864746-93653280-b8e0-11eb-9bad-624bc8f64d6f.png)
![image](https://user-images.githubusercontent.com/18604774/118864740-9102d880-b8e0-11eb-9d1e-ba8a2aa956cd.png)

**Comment by SonGorLick** [comment]
Are you still having this problem on the most recent update
