### ISSUE TITLE
Crash when meeting xenogen news

### ISSUE THREAD

**Issue by Slauenza12** [Dukko/mergerofmods#32]
**Describe the bug**
when i finish first contact for Xenogen news i crash

**To Reproduce**
finish a first contact with Xenogen news

**Expected behavior**
game will crash

**Screenshots**

**Collection info (please complete the following information):**

**Additional context**

**Comment by Slauenza12** [comment]
i pressed the wrong button and opened too soon

**Comment by Dukko** [comment]
Confirmed. I am removing the mod for the time being.
