### ISSUE TITLE
Technological Singularity technology summit doesn't give the 6 months of research points

### ISSUE THREAD

**Issue by Zackman634** [Dukko/mergerofmods#34]
**Describe the bug**
The ascendency perk is supposed to give 6 months of points when the technology summit event fires off every 3 years, but it doesn't.

**To Reproduce**
Get the perk, wait 3 years.

**Expected behavior**
Get 6 months of points, and rapidly finish tech

**Collection info (please complete the following information):**
3.0.3

**Comment by Dukko** [comment]
I am getting the 6 months of research points, not sure why you aren't. Anyone else experiencing this?
