### ISSUE TITLE
Unity massively breaks every time I load the game

### ISSUE THREAD

**Issue by Zackman634** [Dukko/mergerofmods#35]
**Describe the bug**
I've been playing with one of the edicts that increases my unity production, but for some reason, every time I load the game up, I get upwards of 1 Mil. I'm not complaining, but a little weird.

**To Reproduce**
Currently I've used the cheat policy the up my unity production (for fun), but that's about it. I'm not really sure.

**Expected behavior**
I expected my unity count to be the same as before.

**Collection info (please complete the following information):**
3.0.3

**Comment by Dukko** [comment]
Avoid using the unity cheat. It is not balanced for the changes added by Relytor's Empire United. If you need unity, use console.
