### ISSUE TITLE
Admiral Levels aren't leveling up.

### ISSUE THREAD

**Issue by Zackman634** [Dukko/mergerofmods#36]
**Describe the bug**
Doesn't seem to be leveling over time. My top admiral has 0 in all stats, and started with 0. I've had her for awhile now, but no progress.

**To Reproduce**
Unsure. Play with an admiral for a bit.

**Expected behavior**
I expect her to gain levels, but she doesn't.

**Collection info (please complete the following information):**
3.0.3.

**Comment by Zackman634** [comment]
I want to give a heads up, it might only be a glitch. I haven't been watching closely, but my other admiral is leveling up. Either way, it's still a bug, just super specific

**Comment by Dukko** [comment]
Can't replicate at all.
