### ISSUE TITLE
Matrioshka CTD

### ISSUE THREAD

**Issue by Dukko** [Dukko/mergerofmods#4]
Do not use the Matrioshka world from Expanded Gestalts (terraforming option, not the megastructure with same name from Giga). It will result in CTD. Mod author is investigating why

**Comment by LordOfLA** [comment]
Should be fixed in the recent Expanded Gestalts release. You'll need to merge a one-line change with my districts patch until I get to updating said patch.

**Comment by Dukko** [comment]
Thanks for the heads up! I will close this once I can verify.

**Comment by Dukko** [comment]
Missed a changelog for Expanded Gestalts. Thank you @LordOfLA for the ping. Issue resolved.
