### ISSUE TITLE
Eco-Social economy civic (Twinks Paradise Initiative mod) Bio polymer chemist job is missing 

### ISSUE THREAD

**Issue by TheEvilHatter** [Dukko/mergerofmods#41]
**Describe the bug**
When using the 'Eco-Social economy' civic, from the Twinks Paradise Initiative mod, the Bio Polymer chemist job is missing.

**To Reproduce**
Create an empire with the  'Eco-Social economy' civic, or use the prescripted Paradise Initiative empire. Create a Bio-polymer factory or an Eco Industrial District 

**Expected behavior**
Bio-polymer factory or an Eco Industrial District should produce Bio polymer chemist jobs.

![Eco-Social economy Jobs](https://user-images.githubusercontent.com/6956680/120941231-6b1b6780-c719-11eb-97ab-acab3e2b2ed6.png)

**Comment by Dukko** [comment]
I don't touch anything re: those jobs, so idk what could be happening?
