### ISSUE TITLE
Criminal Heritage Does Not Appear

### ISSUE THREAD

**Issue by DoubleE17** [Dukko/mergerofmods#43]
**Describe the bug**
Criminal Heritage civic does not show for Megacorp or Familial Megacorp in empire creation.

**To Reproduce**
In empire creation, look for the Criminal Heritage civic and notice it not being there.

**Expected behavior**
Criminal Heritage to be selectable.

**Collection info (please complete the following information):**
 - Dick 1.03 & Dick 1.02

**Additional context**
I have not added any other mods and had the issue on the previous version and on the new version of the collection using the latest update of irony with the total package of the collection. Maybe I am blind but I looked over the civics many times (including the greyed out options) and could not find criminal heritage anywhere.

**Comment by Dukko** [comment]
Ah, found the bug. Thanks! Should be fixed without the need for an update
