### ISSUE TITLE
Building Adjustments Mod Changes Not Working

### ISSUE THREAD

**Issue by DoubleE17** [Dukko/mergerofmods#44]
**Describe the bug**
The changes made to Alien Zoos and Batharians Power Plants by the Building Adjustments https://steamcommunity.com/sharedfiles/filedetails/?id=1987437371 mod are not applying.

**To Reproduce**
Build an Alien Zoo or Betharian Power Plant and notice that they still have the unmodded effects.

**Expected behavior**
Alien Zoo should have one more of each job and cost double to build, the Betharian Power plant should cost double to build and give 2 more technician jobs.

**Collection info (please complete the following information):**
 - Dick 1.03

**Additional context**
I fixed the issue myself by editing the files in Stellaris\mod\IronyModManager_(Merged)_Dick_1.03\common\buildings and then searching for the building_xeno_zoo and building_betharian_power_plant files and editing the changes to match the Building Adjustments mod.

**Comment by Dukko** [comment]
Fixed in 2.0 (kinda, changed a bunch of things re: buildings so this does not apply anymore)
