### ISSUE TITLE
Arcane Precurson don't give special resources/modpack block new type distric

### ISSUE THREAD

**Issue by xaxunio** [Dukko/mergerofmods#45]
**Describe the bug**
I select specivic civic Arcane Precurson. Distric don't create special resources. Or modpack game block specific new distric.

![image](https://user-images.githubusercontent.com/35309130/121776178-bacfb800-cb8b-11eb-9739-61dc1bea2f17.png)

**To Reproduce**
- Include Empire type/civics/etc if relevant
![image](https://user-images.githubusercontent.com/35309130/121776287-49dcd000-cb8c-11eb-9d80-a87012e23948.png)

**Expected behavior**
I start game with my race and don't  have a special resource from my 1st world..

**Screenshots**

**Collection info (please complete the following information):**

  1.04 
but bug was in 1.03

**Additional context**

I don't change modlist and I don't give new mod from modpack. I delete all files from \Documents\Paradox Interactive\Stellaris\mod before install 1.04 modpack. I download latest version irony menager.

This trait must give me that many tech?
![image](https://user-images.githubusercontent.com/35309130/121776362-b6f06580-cb8c-11eb-81b9-3abd4b228083.png)

greetings
Xaxunio

**Comment by Selkor1** [comment]
You need the origin as well to start with the well eternity, alternatively, you can instant build the building that allows you to build the leyline district. Although really the answer is, just play the prescripted empire.

**Comment by Dukko** [comment]
What Selkor1 said. Not a bug of the collection.
