### ISSUE TITLE
All ships are black boxes, am Only using collection plus collection files. 

### ISSUE THREAD

**Issue by Valdrrak** [Dukko/mergerofmods#47]
**Describe the bug**
All the ships are black squares, Game crashes when I try to launch a game after selecting a faction.

**To Reproduce**

1. Steps to reproduce the behavior:
2. Followed the instructions - Downloaded the collection off the steam workshop, let its do its thing for a while (was 11-13GB total download) then I downloaded the rar "dick 2.10". 
3. Ran the Irony MM, saw the mods from the workshop there, Clicked the import button, selected the "dick 2.10" rar folder, it important them but had and issue and listed about 20 mods were not downloaded even though steam said they were and they were subscribed to, So I went to each mod it listed and unsubscribed and resubscribed to get it to redownload. 
4. Validated my game, rebooted steam then opened the Irony MM again.
5. This time I deleted the previous import attempt and re-imported it, no issues this time, then I hit "Merge" then "compress" and waited for that to complete.
6. Launched the game via Irony MM with the same issues

**Expected behavior**
The ships should display their models, and the game should not crash when I launch it.

**Screenshots**
showing the launcher ( I have not hit conflict solver ) - https://imgur.com/a/3BeefrI
showing the main issue, all ships are broken - https://imgur.com/a/mkiWx1F

**Collection info (please complete the following information):**
"The Merger of Mods [3.0.* STABLE]" && "dick 2.10 collection files"

**Additional context**
Other then the issues with the workshop or Irony MM not downloading or registering mods correctly the rest of it was fine.
crashes after selecting faction, then galaxy settings and after the game has loaded at 99% is crashes to desktop.

**Comment by pat227-hub** [comment]
I am also experiencing the same issue. 
same description as the above

**Comment by ctsv4vendetta** [comment]
Same and I've tried multiple things to remedy the issue. I don't have the crash issue, just the black box ships. Even the DLC ships I haven't purchased are black boxes. Merge takes 10 minutes, game boots in less than 2 minutes, game starts in just a few minutes as well.

**Comment by Dukko** [comment]
Fixed in 2.20. Update 👍
