### ISSUE TITLE
L-Gates Disappearing/Breaking Once Activated

### ISSUE THREAD

**Issue by DemonDestroyer437** [Dukko/mergerofmods#49]
**Describe the bug**
When unlocking the L-Gate, be it the AI or yourself with science ship, the Gates all break and disappear turning into a megastructures that's "_Desc"

**To Reproduce**
Have had this happen with 2 games. The first one I ignored as a bug when trying to switch the imports (the Lem 3.1 versions). Simply happened when the L-Gate Activated event happened.

**Expected behavior**
L-Gates to stay and function normally. All other aspects of nanotech work normally.

**Comment by Dukko** [comment]
Very bad. Let me check what could be happening.

**Comment by DemonDestroyer437** [comment]
Just playing a new run with, I believe, your Lem collection from 10/12 or 10/13, and L-gate functioned normally, didn't break. So might not be an issue anymore with your latest versions.

**Comment by Dukko** [comment]
Yep, it should be fixed. Thanks!
