### ISSUE TITLE
Mods no longer available

### ISSUE THREAD

**Issue by EnraNZ** [Dukko/mergerofmods#60]
**Describe the bug**
I just installed the game again in version 3.3.4, subscribed to all the mods and downloaded them.
After importing the Libra.zip in Irony, I'm getting a message that two mods are missing. 

The following mods could not be imported as they appear to be missing:
Ascension Perks Mega Patch (mod/ugc_2782032385.mod)
Galactic Community Expanded Defines (mod/ugc_2312203163.mod)

**To Reproduce**
Follow the instructions

**Expected behavior**
There should be no such error msg in Irony.

**Collection info (please complete the following information):**
 - Version 3.3.2 - Irony.zip

**Additional context**
The Galactic Community Expanded Defines seems to be available on Steam under another ID, for the Mega Patch there are 3 different versions available. Should I use any one of these or are there offline copies available that I can use? thx

**Comment by DiettingerX** [comment]
Ascension Perks Mega Patch (Original ESAP version) (Updated 2022 05 02 May)
https://steamcommunity.com/sharedfiles/filedetails/?id=2802886177&searchtext=Ascension+Perks+Mega+Patch

Galactic Community Expanded Defines (Updated 2021 11 22 Nov)
https://steamcommunity.com/sharedfiles/filedetails/?id=2312203163&searchtext=Galactic+Community+Expanded+Defines

**Comment by Dukko** [comment]
I don't support old versions, they're left for people to tinker with.
