### ISSUE TITLE
Void Dwellers Expanded Bug?

### ISSUE THREAD

**Issue by IntegralAnarchy** [Dukko/mergerofmods#61]
Hi,

I can't seem to use the archeology project planetary decision from this mod though I've completed all the requirements for enacting said decision. Running latest collection: Cepheus 3.4

Anyone else encounter this problem?

Last screenshot is showing civics/leader traits.
![Screenshot (1)](https://user-images.githubusercontent.com/106932120/172070729-4588ca17-1ff8-45f8-91f8-ac879d10bbf9.png)
![Screenshot (3)](https://user-images.githubusercontent.com/106932120/172070733-655e3a81-448a-4264-a45a-f54183dd8c8b.png)

**Comment by Dukko** [comment]
uh, odd. Can you share a save?

**Comment by IntegralAnarchy** [comment]
[](https://drive.google.com/file/d/1UzlGY_1Kga8Qa5hy2yXGlZJ66imaww--/view?usp=sharing)

Last 2 planets are eligible for the conversion.
