### ISSUE TITLE
Duplicate Consumer Goods in Market screen

### ISSUE THREAD

**Issue by herki18** [Dukko/mergerofmods#8]
![image](https://user-images.githubusercontent.com/940910/116796708-a43b3900-aad6-11eb-9484-44856dccfb7d.png)

**Comment by herki18** [comment]
![image](https://user-images.githubusercontent.com/940910/116799727-bc20b600-aaf2-11eb-82ef-3287f5b5a795.png)

**Comment by Dukko** [comment]
Thanks, I know why this is happening. Will fix it in next update

**Comment by Dukko** [comment]
Should be fixed @herki18. Can you confirm?

**Comment by herki18** [comment]
It seems it is now fixed thanks
