### ISSUE TITLE
Fallen Empires and marauders are not generated properly

### ISSUE THREAD

**Issue by herki18** [Dukko/mergerofmods#9]
![image](https://user-images.githubusercontent.com/940910/116880100-7c082300-ac19-11eb-82e4-80df15d5dc5f.png)

![image](https://user-images.githubusercontent.com/940910/116880448-ee790300-ac19-11eb-8f26-9853995d1fd8.png)

**Comment by herki18** [comment]
![image](https://user-images.githubusercontent.com/940910/116881275-f5544580-ac1a-11eb-8132-6f1864e50074.png)

**Comment by herki18** [comment]
It seems More Natural Looking Galaxis issue. 

I added Yet Another Galaxy Enhanced Galaxy back in and it works perfectly 

![image](https://user-images.githubusercontent.com/940910/116903031-c8f8f300-ac33-11eb-8041-563268b8f8bb.png)

**Comment by Dukko** [comment]
Cannot replicate. Anyone else with this issue?
